### ISSUE TITLE
Search results are sorted randomly

### ISSUE THREAD

**Issue by DonPicciotto** [vauvenal5/yaga#107]
When I search for a specific date (like 2020), results aren't sorted correctly and months shows randomly (e.g. photos of 2020-06-02 before photos of 2020-03-02 but after photos of 2020-08-02)

**Comment by vauvenal5** [comment]
Thx for reporting! I will have to investigate. Probably the latest performance optimization is responsible for this.

**Comment by DonPicciotto** [comment]
> Thx for reporting! I will have to investigate. Probably the latest performance optimization is responsible for this.

Thanks to you for your work :)

**Comment by vauvenal5** [comment]
Are you still able to reproduce this on `v0.23.1` or later?

**Comment by DonPicciotto** [comment]
Yep, when search e.g. 2021 month-day blocks are sorted randomly. I could try cleaning app data or uninstalling and reinstalling the app, if you think this can be helpful.
I'm using Yaga 0.23.2 on f-droid

**Comment by vauvenal5** [comment]
Okay, can you in this case do it one more time and afterwards send me the logs? You can find a `Send Logs`-button in the general app settings.

Edit: Best to my Github email.

**Comment by DonPicciotto** [comment]
Ehy, sorry for asking, it's just to be sure: I sent logs to you a couple days ago, did they get to your mail?

**Comment by vauvenal5** [comment]
Hi! Yes I got them, just didn't have any time to work on it recently.

**Comment by DonPicciotto** [comment]
No problem, thanks for the answer :)

-------- Messaggio originale --------
On 1 apr 2021, 11:38, vauvenal5 ha scritto:

**Comment by vauvenal5** [comment]
Should be fixed in `v0.23.12`. Thx for reporting and your help.

**Comment by DonPicciotto** [comment]
Thanks to you for your work!

-------- Messaggio originale --------
On 5 apr 2021, 22:27, vauvenal5 ha scritto:
