### ISSUE TITLE
Feature request: allow HTTP connection

### ISSUE THREAD

**Issue by andriuski** [vauvenal5/yaga#115]
Hi,
There are cases when nextcloud is run in a home environment and SSL is not really necessary and it is run over HTTP. Currently the app does not accept HTTP addresses and if such address is entered it says that 'https will be added automatically'.

Andrius

**Comment by vauvenal5** [comment]
Sorry I do not plan on adding support for HTTP. Now a days it is a too big security issue. Even when run in a home environment.

**Comment by AbsurdlySuspicious** [comment]
I believe that for trusted environments (like private openvpn networks) this just adds more useless work with self-signed certs and unnecessary overhead for double-encryption. "I know what I'm doing" option wouldn't hurt that much
