### ISSUE TITLE
Invalid server address if the last char is a space

### ISSUE THREAD

**Issue by n7otz3n938t3** [vauvenal5/yaga#122]
I was confused for a moment why my address was wrong until I found out

![CollageMaker_20210410_025201790.jpg](https://user-images.githubusercontent.com/81805679/114253394-4d948080-99aa-11eb-8e79-76d409647e47.jpg)

**Comment by vauvenal5** [comment]
Yes, trimming should happen automatically. Thx for reporting!

**Comment by vauvenal5** [comment]
fixed in `0.25.1`
