### ISSUE TITLE
share picture to other Apps

### ISSUE THREAD

**Issue by Happyfeet01** [vauvenal5/yaga#133]
Hello,

I tried to share an Photo to an other App. But the App force-close. I got this Error Message:

`[Fehler]:
1 Bild(er) wurden wegen Fehlern nicht bearbeitet! Bitte sicherstellen, dass der Zielordner existiert und erlaubt vollen Schreibzugriff. Für mehr Details - s. Fehlerbericht.
(Shared from: com.github.vauvenal5.yaga)
#1 - Source image not found: /external_cache/share/IMG_20200828_152528.jpg

[Daten des Geräts]:
ELS-NX9, API 29, Build 3004, Display 1200x2227, Density 3.3125, Heap 512mb, Target g/b: 2592x3840/0x0@32bit, Locale: DEU (de_DE)
Storage 0: /storage/emulated/0 (total: 233842mb, free: 189415mb)
Storage 1: /storage/0123-4567 (total: 119248mb, free: 72879mb)`

How can i share Pictures correctly?

**Comment by vauvenal5** [comment]
Thats odd. I myself use the share future on regular basis to send pictures to friends. Can you tell me what app you were sharing to? Also does the picture which you want to share have a green circle in the right bottom corner?

**Comment by Happyfeet01** [comment]
Hi,

in This Case from Yaga to Matrix Messenger. I also tried over the Download Button. But can find the downloaded image.

**Comment by Happyfeet01** [comment]
For me it works now. Also with the element (Matrix) or Childichat, Signal ...i think it can be closed.
