### ISSUE TITLE
Login doesn't advance

### ISSUE THREAD

**Issue by junetried** [vauvenal5/yaga#136]
I have no idea how to troubleshoot at this point, so I'll just [attach a log](https://github.com/vauvenal5/yaga/files/6413088/yaga.isolate.log.txt).

When trying to log in, the 'Open in browser' and 'Continue' buttons do nothing when I type my host. Initially I thought it was because my nginx configuration trims /index.php, but I don't have much reason to believe that at this point. What I *do* know is that it works fine under my apache configuration, after trusting the self-signed certificate (the CA has been added in android settings). Switching back to nginx after logging in with apache running doesn't work around this issue.

I'm not sure the log is very useful, it doesn't give much insight. Don't know what `TLSV1` is doing there, Firefox assures me the host is using TLSv1.2.

**Comment by vauvenal5** [comment]
Hi! Anything interesting in the 2nd log file? It looks like for some reason your proxy suggests a TLSv1 connection. Not sure that I can do something about that.

**Comment by junetried** [comment]
Nothing in [the other log](https://github.com/vauvenal5/yaga/files/6413997/yaga.log.txt) looks interesting, no.

Looking back at my nginx config, I have these two lines:
```
ssl_protocols TLSv1.3;
ssl_prefer_server_ciphers off;
```

Yet Firefox prefers to use TLSv1.2? Going to Google and checking encryption info, no issues with TLSv1.3 support... This is weird, and it might be an issue on my end.

**Comment by vauvenal5** [comment]
#100 had similar issues maybe this helps.

**Comment by runhard48-6** [comment]
I was having a similar issue, #127, and as soon as I allowed TLS 1.2 the login screen would advance and the app works just fine now. In my case, I had to adjust the TLS via Cloudflare, as that is where I had it set to 1.3 only.

**Comment by junetried** [comment]
> I was having a similar issue, #127, and as soon as I allowed TLS 1.2 the login screen would advance and the app works just fine now. In my case, I had to adjust the TLS via Cloudflare, as that is where I had it set to 1.3 only.

Allowing TLSv1.2 fixes this, the app logs in just fine now. Thanks!
