### ISSUE TITLE
Home View is empty after configuring root mapping as documented

### ISSUE THREAD

**Issue by zsolt-donca** [vauvenal5/yaga#139]
I configured the root mapping following the [documentation](https://vauvenal5.github.io/yaga-docs/sync_flow/) for the second option, which is when Nextcloud is configured to keep the files where they are. With this setup, the Home View is completely empty. 

This is how the settings page looks like:

<img src="https://user-images.githubusercontent.com/6824167/117552965-4fa83880-b057-11eb-9091-54f0547f7cdc.png" width="400">

When I configure the local and remote paths, I see the same files with the same previews, so I think I am configuring them correctly.

I am using Yaga v0.25.3, installed from F-Droid, and using Lineage OS 18.1, Android 11. My NextCloud server is also the latest (it is a fresh install, actually), version 21.0.1.1.

**Comment by vauvenal5** [comment]
Hey!

Sorry for the late response. What you have configured is the behavior for were to search for files locally and were to store downloads. You are probably still missing the configuration of what to display in your home view: https://vauvenal5.github.io/yaga-docs/quickstart/#set-home-view-path

**Comment by mooninite** [comment]
I upgraded from NC 19 to 20 and Yaga stopped pulling up new phone photos. I could still see and download old photos. After wiping out app data and logging back in my home view is now blank. Browse view shows my photos folder as empty, too, but I can see pictures in different folders outside of my phone photos folder.

The NC app shows all photos present and it is successfully uploading new photos through auto-upload. I can also see all of my photos through a web browser.

**Comment by vauvenal5** [comment]
@mooninite can you send me your logs as well as a screenshot of your global and home view settings by email?

**Comment by vauvenal5** [comment]
@zsolt-donca is your original issue still unresolved?

**Comment by zsolt-donca** [comment]
@vauvenal5 sorry for the late response. The issue is resolved indeed, the setting that you mentioned in the home view did indeed solve the issue.
