### ISSUE TITLE
slideshow support

### ISSUE THREAD

**Issue by tclavier** [vauvenal5/yaga#141]
In one directory I want to show all photos as a slideshow with recursive option

**Comment by vauvenal5** [comment]
Sorry can you elaborate more on this? Did you try browsing to that directory and switching to `Focus View`?

**Comment by tclavier** [comment]
When I think recursive slideshow, i think : 
* in full screen
* with an autoplay
* they find all pictures in all subdirectory

In `Focus View` the recursive option is ok, but I don't find the autoplay slideshow, and in single photo view, after the last photo in one directory it's impossible to slide to the first photo in next directory.

**Comment by vauvenal5** [comment]
I can consider this in future however currently I have more pressing issues.

Btw in `Focus View` if you change the `View Type` from `Category View` to `Grid View` you will have the option to slide over all images.

Regarding full screen there is already an open issue: #108

**Comment by do1fmd** [comment]
It would be really awesome, if this enhancement could get implemented.

**Comment by vauvenal5** [comment]
This has been implemented in v0.29.2.
