### ISSUE TITLE
Home view empty after NC 19 to 20 upgrade

### ISSUE THREAD

**Issue by mooninite** [vauvenal5/yaga#145]
Yaga version 0.26.1
Repo: F-Droid
Phone: Pixel 3 (June 2021 firmware)
Nextcloud 20.0.8
Server OS: Fedora 34 x86_64

After upgrading my Nextcloud server from 19 to 20 the Home View in Yaga became stagnant. I took new photos but they did not show up in Yaga. They do show up from the Nextcloud Android app or from a web browser.

Clearing the app data/cache and logging back in resulted in a blank home view.

Yes, Root Folder and General Path are set to correct values. Changing the General Path to a different folder with images in it shows those images. Changing back to my phone photos shows an empty home view.

I will email you the most recent logs.

**Comment by KruyKaze** [comment]
I just discovered Yaga and I'm on NC20 . I can confirm that no photos show up in home view.
Thanks for looking into this

**Comment by chrismin13** [comment]
Same problem here but with Nextcloud 21!

**Comment by vauvenal5** [comment]
@mooninite I finally had a chance to look into your logs. Short questions if you change your `Home View -> View Type` to `List View` you still do not see any images?

It probably is not related to the Nextcloud version since I myself am running NC21.

**Comment by mooninite** [comment]
Changing View Type to any type, List, Grid, etc. does not display the photos.

**Comment by DecaTec** [comment]
I just discovered this app and it really sounds great if you don't want to double your pictures on the phone and in the cloud.
But I also can confirm that issue (meanwhile NC 21.0.4).

In the app's logs there is nothing really interesting:
```
2021-08-17 16:28:23.548781 WARNING FileListLocalManager - 9755d7a0-ff3f-11eb-a5dc-0df65fd8336d (start)
2021-08-17 16:28:23.553727 WARNING FileListLocalManager - 9755d7a0-ff3f-11eb-a5dc-0df65fd8336d (received list - #images: 0)
2021-08-17 16:28:23.554081 WARNING FileListLocalManager - 9755d7a0-ff3f-11eb-a5dc-0df65fd8336d (done - manager key)
2021-08-17 16:28:23.554148 WARNING FileListLocalManager - 9755d7a0-ff3f-11eb-a5dc-0df65fd8336d (done - event key)
```

Would be great if this would be fixed!

**Comment by vauvenal5** [comment]
First of all sorry for the slow response. I am currently under water at work.

2nd, is your browse view also empty?

**Comment by Happyfeet01** [comment]
Hello,

under NC 22.1.1 the same Problem. Homeview Tab is empty, when the Path is set to Nextcloud.

the Browse View Tab wont show any Photo.

**Comment by DecaTec** [comment]
> 2nd, is your browse view also empty?

No, the browse tab is working correctly.
It's only the home tab which would be the most useful part of the app.

**Comment by vauvenal5** [comment]
Have you done the following? https://vauvenal5.github.io/yaga-docs/assets/videos/change_path.gif

**Comment by DecaTec** [comment]
> Have you done the following? https://vauvenal5.github.io/yaga-docs/assets/videos/change_path.gif

That was the missing link for me...thanks!

Maybe it's a good idea to put a link to the docs in the Readme of the project? I just missed the link in the about section...

**Comment by Happyfeet01** [comment]
Okay.

That works, but it wont show the Pictures at the subfolder YYY/MM.

03.09.2021 10:03:45 DecaTec ***@***.***>:

**Comment by Happyfeet01** [comment]
It seems its preview Picture/cache Problem from my Cloud? But i don't know. When Yaga loads the pictures from the Upload folders, the Pictures are showing at the Homeview Tab.

Problem is solved for me.

03.09.2021 10:24:34 Lars Müller ***@***.***>:

**Comment by Happyfeet01** [comment]
After an Reset nothing works. I dont no why
![Screenshot_20210910_212220](https://user-images.githubusercontent.com/3295104/132906610-f04fd6c6-bb35-4c13-841f-3e1874e9d16a.jpg)

**Comment by Happyfeet01** [comment]
Sometimes working, sometimes not.

I have a lot of warnings in the Log file.
[yaga.log.txt](https://github.com/vauvenal5/yaga/files/7149010/yaga.log.txt)

**Comment by vauvenal5** [comment]
@Happyfeet01 did you grant permissions to the app? For some reason the app is failing to sync the date modified when pulling images. Can you narrow down when it is working and when not? What is different when it works?

**Comment by kojid0** [comment]
> Have you done the following? https://vauvenal5.github.io/yaga-docs/assets/videos/change_path.gif

Had the same issue, this solved it for me. Thank you!

**Comment by Happyfeet01** [comment]
> @Happyfeet01 did you grant permissions to the app? For some reason the app is failing to sync the date modified when pulling images. Can you narrow down when it is working and when not? What is different when it works?

Sorry for the late response. 

I made an fresh Setup from the gallery App.  When choose  at the Homeview Tab the Path to my uploads i can't see any files. 
When i select the remoteview Tab, choose my cloud and browse to Path for the camera uploads (Kamerauploads/2021/11)  the images are loaded and these Pictures are visible at the Homeview Tab.  But only when i tab on each folder at the remoteview tab.  

It seems the Homeview Tab can't load recursive.

**Comment by mooninite** [comment]
Duplicate of issue #97 because of the bad handling of missing last modification dates.

For some reason (Nextcloud app bug?) I had 3 files out of 3000 that had a zero'd last modification date. Setting the date to the real one let Yaga load my photos and they all load fine.

Should probably raise the priority of gracefully handling bad dates on files. :)

For those that may not know about setting last modified date:

Navigate to your cloud storage directory on the Nextcloud Server and run the touch command:
`touch -d "<RFC 5322 date string>" filename.jpg`
example:
`touch -d "Mon, Dec 20 2021 13:39:01" IMG20211220_133901.JPG`
