### ISSUE TITLE
Don't download images

### ISSUE THREAD

**Issue by gomme600** [vauvenal5/yaga#148]
Hi, I just found this app. There is something I don't quite understand, whenever I click on a photo it seems to be downloaded to my device. After a while this will take up a lot of storage space! Are these images cached and then removed automatically at a later time or will I end up with a local copy of every image I view?

Thanks

**Comment by vauvenal5** [comment]
Hi. Sorry for the late response quite a lot to do @ work currently. You can disable this behavior in the global settings. See also #82 and #83.

**Comment by vauvenal5** [comment]
Closing this.
