### ISSUE TITLE
Sign In Site brings me directly to Nextcloud

### ISSUE THREAD

**Issue by davidbecker808** [vauvenal5/yaga#160]
The Sign in Page brings me directly to the Nextcloud login and after logging in I see the Nexcloud Web Interface like a normal Browser.

Version: v0.27.1

**Comment by vauvenal5** [comment]
Hi! Sorry for the late response. Were you able to resolve your issue?

**Comment by davidbecker808** [comment]
Hi, i don't know, but when i tried it a few days later it worked just fine. Even though it was the same version.
Now it works :)
