### ISSUE TITLE
Not showing any images 

### ISSUE THREAD

**Issue by MaggiWuerze** [vauvenal5/yaga#42]
After logging in successfully the app isn't showing any images in the "Home View".
When navigating through the explorer I can see my pictures.

Resetting the root folder and checking recursive search did not help. 

Android 10
Nextcloud 20
App 0.15.10

**Comment by vauvenal5** [comment]
Hi! Did you change the `path` in the home view settings? 

As described here: https://vauvenal5.github.io/yaga/quickstart/#set-home-view-path

**Comment by MaggiWuerze** [comment]
That fixed it, thanks
