### ISSUE TITLE
Android app feedback

### ISSUE THREAD

**Issue by jcm4atx** [vauvenal5/yaga#46]
I don't have an issue per se, but rather I'm sharing my thoughts on the app.

Right off the bat I had the issue with the ERR_CLEARTEXT_NOT_PERMITTED problem, but a simple Google search revealed the solution which I (poorly) documented on [my wiki](https://johnmayson.com/wiki/computing/nextcloud_notes). 

**What I like**
1. It's fast. I'm running my Nextcloud off a Raspberry Pi and the app works great.
2. It's simple.

**Enhancements I'd like to see**
1. Support for video.
2. Ability to edit/delete/move.
3. Ability to edit/add/view metadata.

I would happily pay $5 for an app that did what I listed above.

**Comment by vauvenal5** [comment]
Hi! Thanks for the feedback. Regarding your feature requests:
1. will come at some point and is documented in #45 
2. 
   1. delete/move are coming and are tracked in #27 and #28 
   2. edit strongly depends on what you understand by editing... however, currently I am not planing any kind of image or video editor... I think there are more then enough apps out there that do only this and they do it pretty well.
3. That sounds reasonable. Would you mind opening a separate issue to track the metadata feature request?

Closing this issue in favor of the specific feature issues, feel free to reopen it if you want to discuss something further.

**Comment by jcm4atx** [comment]
Thank you for the response. I opened #49
