### ISSUE TITLE
Not able to fetch data when Nextcloud behinde subpath instead of root domain

### ISSUE THREAD

**Issue by vauvenal5** [vauvenal5/yaga#52]
both me and @aginies are using the same instance:

from the logs, I noticed (I replace the server real hostname to www.foobar.com in the logs,  nextcloud is installed in https://www.foobar.com/nc/ ):

[01-08 13:56:06.147 12347:13828 I/flutter]
[38;5;208m[W] NextcloudFileManager - Emiting list! (nc://fcrozat@www.foobar.com/nc/)[0m

[01-08 13:56:06.147 12347:13082 I/flutter]
[38;5;208m[W] FileListLocalManager - deb12f60-51b0-11eb-b74e-21838d65f07b (done - manager key)[0m

[01-08 13:56:06.148 12347:13082 I/flutter]
[38;5;208m[W] FileListLocalManager - deb12f60-51b0-11eb-b74e-21838d65f07b (done - event key)[0m

[01-08 13:56:06.148 12347:13828 I/flutter]
404

[01-08 13:56:06.148 12347:13828 I/flutter]
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name //nc could not be located</s:message>
</d:error>

_Originally posted by @fcrozat in https://github.com/vauvenal5/yaga/issues/41#issuecomment-756747921_

**Comment by vauvenal5** [comment]
I believe it has something to do with your Nextcloud being behind a subpath instead behind your root domain. I have to check my path handling logic. However reproducing this might be more difficult since my Nextcloud setup is fundamentally different.

@fcrozat any chance you could provide a temp test account on your Nextcloud instance?

**Comment by adrianreber** [comment]
I see the same problem. Changing into a subdirectory gives me following log in web server using yaga:
```
"PROPFIND /owncloud/remote.php/dav/files/adrian/owncloud/test-directory/ HTTP/1.1" 404 238 "-" 810 1588 "Dart/2.10 (dart:io)"
```

Using the Nextcloud web interface I see following access:
```
"PROPFIND /owncloud/remote.php/dav/files/adrian/test-directory HTTP/2.0" 207 4057 "-" 748 4321 "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
```

So, yaga, is adding an additional `owncloud/` to the request.

**Comment by aginies** [comment]
> I believe it has something to do with your Nextcloud being behind a subpath instead behind your root domain. I have to check my path handling logic. However reproducing this might be more difficult since my Nextcloud setup is fundamentally different.
> 
> @fcrozat any chance you could provide a temp test account on your Nextcloud instance?

WIll send you an email with credentials.

**Comment by vauvenal5** [comment]
Thx for the credentials. I will look into it this week and hopefully publish an update until end of week.

**Comment by vauvenal5** [comment]
Okay, the good news first, I found the bug and a quick fix is possible. However, it showed up a deeper issue which has to be addressed at some point. I have to consider if it is a good idea to fix this now as part of this bug fix before I do anything.

Any way I expect a fix until end of week.

**Comment by vauvenal5** [comment]
Should be fixed in `v0.17.5`.

**Comment by vauvenal5** [comment]
Can I close this?

**Comment by fcrozat** [comment]
Yes, it works fine now !

**Comment by aginies** [comment]
ok, this is working now. Thanks for the fix.
