### ISSUE TITLE
App won't load

### ISSUE THREAD

**Issue by galaxyrun** [vauvenal5/yaga#75]
Version: 0.19.1

When I open Yaga and activate Category View, the app freezes. 

I think it is because of the synchronization of the images. When flight mode is enabled, the app does not freeze.

Btw grid view does work.

**Comment by vauvenal5** [comment]
Hi!

Thanks for reporting. I need some additional information, please:
- Do you experience the same behavior in both `Category View` and `Category View (experimental)`?
- How many pictures are in the folder(s) you are loading?
- Can you give an estimate to how many categories you are trying to display? (A category is the date part of the date-modified timestamp.)

In general there are a few performance issues regarding the category view which I have not managed to fix yet. It has to do with the way Flutter is calculating if the display is full or not.

**Comment by luckkmaxx** [comment]
For me the app freezes always while loading/opening the app. Just leave it a few seconds until upper loading bar gones. Then it goes well (no freezes) until I slide down to get updates, so it freezes a few seconds again.

**Comment by vauvenal5** [comment]
@luckkmaxx can you provide some additional information:
- Which version of the app are you using?
- Do all view types behave in the same way?
- Does this happen for all your image locations or do only folders with a lot of images freeze?
- How many images are you loading?
- What kind of device do you have?

Thanks!

**Comment by luckkmaxx** [comment]
> @luckkmaxx can you provide some additional information:
> - Which version of the app are you using?
> - Do all view types behave in the same way?
> - Does this happen for all your image locations or do only folders with a lot of images freeze?
> - How many images are you loading?
> - What kind of device do you have?
> 
> Thanks!

- v0.21.1

- Yes, seems to be the background process of getting images. No matter if you are in home view (in any view type) or browsing folders in the browse view. While is getting images (I think the timeline) the whole app freezes until images are given.

- So I have about 10.000 images being loaded in the timeline.

- Im using a Xiaomi RN8T (a.k.a. willow)

- Thank you!

**Comment by galaxyrun** [comment]
> For me the app freezes always while loading/opening the app. Just leave it a few seconds until upper loading bar gones. Then it goes well (no freezes) until I slide down to get updates, so it freezes a few seconds again. 

It's exactly the same for me. I have the newest Update now v.0.21- same issue there

**Comment by vauvenal5** [comment]
Could be the sorting algorithm. It is the only time-consuming thing left in the UI thread. Everything else is in a 2nd thread. I will move the list sorting to the background and we will see if it changes anything. :+1:

**Comment by vauvenal5** [comment]
Hey! I just published `v0.21.5`, let me know if this improves the app behavior for you.

**Comment by luckkmaxx** [comment]
> Hey! I just published `v0.21.5`, let me know if this improves the app behavior for you.

Yes! Now when I open yaga, 3 seconds later the photos are showing and the progress bar works while I can swipe down to older images. No freezes, just a little laggy, but very fine! Thanks, your work seems to be in the right way!

**Comment by vauvenal5** [comment]
If you have no objections I will consider this closed for the time being. Further improvements require reworking the whole approach of how files are retrieved, see #80. The main issue boils down to the amount of files and that they are all being loaded at once.

Regarding any lag during scrolling, the `Category View (experimental)` seems to have a worse performance when handling a lot of files then the `Category View`. Especially if you have big categories.

**Comment by galaxyrun** [comment]
Looks like this fixed the problem
