### ISSUE TITLE
Stuck in loading screen

### ISSUE THREAD

**Issue by LukeVader-IV** [vauvenal5/yaga#89]
Hey,
before connecting to my server i don't have any issues and works as I think it's supposed to, however the moment I link it up it doesn't load any images from the server and the moment I close and reopen the app it gets stuck in the loading screen.

Server: CentOS stream (Linode)
Phone: Android 11 (sonny Xperia 10 ii)

I tried the latest version in both  the google play store and F-droid and I tried rolling back to 0.20.3 and 0.15.6 but the issue persists
I can provide you with any other necessary information about the system and configuration

**Comment by LukeVader-IV** [comment]
I tested the app on a Pixel 2a and the exact same thing happens
also, I noticed you are using .png for images that could be made much more efficiently in .svg, is there a reason for this?

**Comment by vauvenal5** [comment]
Hi!

When you login to your server and change to `Browse View` and then tap on your account does it load anything? Also does your user icon get loaded?

Can you elaborate on the png vs svg question? The app should be providing your files like they are on the server.

**Comment by LukeVader-IV** [comment]
So I tried recreating the issue again however It now suddenly seems to work as it should and I haven't changed anything. I'll try to reproduce the issue again when i can so i can post screenshots.

About the .SVG question it was not about the files on the server but the project assets being .PNG like app icon and such.

**Comment by LukeVader-IV** [comment]
So i tried once again to connect the Pixel 2a and the same issue happens once again, here are the screenshots i took:

![signal-2021-02-28-141119_001](https://user-images.githubusercontent.com/15455108/109419755-54a19980-79cf-11eb-85ae-b9828e5a4fea.png)
![signal-2021-02-28-141119_002](https://user-images.githubusercontent.com/15455108/109419763-5d926b00-79cf-11eb-8209-abd2b08fb348.png)
![signal-2021-02-28-141119_003](https://user-images.githubusercontent.com/15455108/109419765-5e2b0180-79cf-11eb-86b1-d609f2b19d96.png)
![signal-2021-02-28-141119_004](https://user-images.githubusercontent.com/15455108/109419766-5ec39800-79cf-11eb-8a1e-39000dca3a62.png)

**Comment by vauvenal5** [comment]
* Are the gray areas actually displayed as gray or did you put them there after taking the screenshots?
* Is this the newest version of the app?
* Can you maybe provide logcat logs?

About the assets, I used generations tools to automatically create them to be honest.

**Comment by LukeVader-IV** [comment]
the Grey areas are not edited in and how it actually looks like.
I downloaded The app from Google play and F-Droid so i assume so and I also tried older versions with the exact same issue, meaning the grey squares and stuck in loading screen
as for the logs I searched the entire phone via USB and didn't find it, where should they be?

**Comment by LukeVader-IV** [comment]
I just realised you wrote 'logcat' so i'll try my best.

**Comment by vauvenal5** [comment]
Logcat logs have to be retrieved with ADB. Its a Android dev tool but if you do not have it don't worry I will think of something else.

It looks like for some reason the app is not able to load the user icon and that leads to the grey areas. I am not yet sure why this happens.

**Comment by LukeVader-IV** [comment]
ok so I was struggling a little with adb logcat but I figured it out
as it's the first time i'm using adb for anything else then rooting i'm not too experienced with it but i copied and pasted the output in some text files, i did it both on the sony where it seems to work now and the pixel where it still doesn't work so you could maybe see the difference
_[edit vauvenal5: removed for security]_

If i accidentally cut something important out, let me know.

**Comment by vauvenal5** [comment]
Hi! Thanks I downloaded them and will have a look if I see anything in there. I removed them from Github to make sure nothing gets leaked by accident.

**Comment by LukeVader-IV** [comment]
oh yeah thanks, I didn't think about that (-:

**Comment by vauvenal5** [comment]
Sadly I do not see anything in the log. Can you by chance try again? Also while recording the log please open the drawer and also navigate to the `Browse View`. And just send it by email if possible, thx!

In the working log I can see how the file list gets fetched successfully.

**Comment by LukeVader-IV** [comment]
I just sent you a new file with logs through email, it should be in your inbox. I didn't have an opportunity to do so before now so sorry for the delay

**Comment by vauvenal5** [comment]
Okay, for some reason the app is not able to load your user information from the server. You have a standard Nextcloud setup? Or did you deactivate the OCS API (not even sure that is possible)?

**Comment by LukeVader-IV** [comment]
well it's a pretty standard setup and I'm pretty sure open collaboration services are enabled by default, also don't forget I did get it to connect to the server on the Sony Xperia and it still works, even though I'm not doing anything different and it didn't work multiple times before

If you know how i could double check it i could try but it doesn't make a lot of sense to me
I could also try disconnecting and reconnecting the Sony and get logs of that

Edit: just to be 100% sure we're on the same page the logs i sent you are logs of my trying to open the app and getting stuck in the loading screen, I now think that something gets saved incorrectly in the app at first connection attempt AKA when you set up the server and after that it tries to communicate with the server and fails causing it to get stuck in the loading screen. So a bug with the app, not an issue with the next cloud server

**Comment by vauvenal5** [comment]
Yes, you are right otherwise it would not work on all devices. It would be great if you can send a full log of an initial login maybe we can then see the original exception and not only the aftereffect. Best would be to uninstall and re-install the to make sure everything is deleted.

If that does not help identify the exact cause I will increase logging output around the code responsible for Nextcloud integration and also around the code responsible for persisting login information locally and publish a new version. However, this will probably have to wait till end of week when I have some more time.

**Comment by LukeVader-IV** [comment]
I sent you the login logs through email, this time it is the Sony (the device that was working) and as i expected it no longer worked after doing this, so it's not something device specific and not something with my network either as i logged in on a different network

**Comment by LukeVader-IV** [comment]
I tried looking at the logs more closely this time and Errors are handily marked in red, I noticed a batch of SQL lite errors that i didn't notice in the other logs.

**Comment by LukeVader-IV** [comment]
i realise that on this network DAVx5 also gives an error and I can't even SSH to the server so these issues are actually probably not caused by the app but by this bad network implementation, I'll send you more logs once I'm back on a decent network

**Comment by LukeVader-IV** [comment]
In the new Logs i no longer see the SQL lite errors but I'm like 90% sure that something gets configured incorrectly at setup and it just never gives up, Is there no way to check whether or not you are actually able to retrieve the necessary information if not and at least cause a pop up with an error? because this way a user will simply think it's taking ages to load.

**Comment by vauvenal5** [comment]
Hey! First of all thanks for the logs you submitted up until now! Very helpful.

I just had a look into your last submitted logs and I can see an exception in there but not the cause of it. I will improve logging and publish a new version which logs out more details.

Regarding your second suggestion, yes, it is one of the open todos to display errors to the user instead of failing silently.

**Comment by LukeVader-IV** [comment]
Great, Just notify me when ya release the new version :)

**Comment by vauvenal5** [comment]
New version is up in the PlayStore. `v0.22.3` contains improved logging. So if you could send me a new logcat file we will hopefully finally find the issue.

**Comment by LukeVader-IV** [comment]
Hey thanks, Unfortunately i don't have access to my tools right now due to unfortunate circumstances, however i should be able to do it this weekend (Sorry to keep you waiting)

**Comment by LukeVader-IV** [comment]
I just sent you new logs through email, however i haven't had the opportunity to check them out myself

**Comment by vauvenal5** [comment]
I had a look and replied to you by mail. For some reason your access to the user information endpoint is denied. Did you do a full re-login while recording the logs? Can you also try if you have the same issue if you login with a app password instead?

**Comment by LukeVader-IV** [comment]
yes it was a log of me logging in after installing the app and I find that weird, does it maybe communicate with any other ports outside of the default http and https ports that might be blocked? also you lost me on the app password part

**Comment by vauvenal5** [comment]
In your Nextcloud go to Settings and then to Security. At the bottom of the page you can manually create an app passwords.
When logging into Yaga at the bottom of the screen there is an option to login with an app password.

![Screenshot_1615723328](https://user-images.githubusercontent.com/1935503/111067604-5ab27280-84c5-11eb-9b75-85033adc9025.png)

**Comment by vauvenal5** [comment]
@LukeVader-IV any nows here? Is this still an open issue?

**Comment by LukeVader-IV** [comment]
hey, yeah sorry for the silence, I broke my phone and I've been way too busy to bring it to a repair shop for the moment, I'll get back to you once I get it repaired

**Comment by LukeVader-IV** [comment]
hey so i know it's been a few months but i was busy doing stuff like my end of year exams but i finally had some free time to try to get more logs and see if the issue is still there, i'm happy to report that the app now behaves as expected

sorry for the silence, but great work (: 👍🏻
