### ISSUE TITLE
Localhost and no SSL

### ISSUE THREAD

**Issue by realquink** [vauvenal5/yaga#92]
Hi,

I can't seem to get it working with my local nextcloud server. I also don't have an SSL on my local nextcloud server. The attached screenshot is what I get when I try to hit the browser button. When I hit trust the popup just keeps popping up and won't accept it seems. I would love to get this working in my local home network. Please let me know if there is anything I can do.

Thanks

![screenie](https://user-images.githubusercontent.com/35575102/110031045-6d2dee80-7d04-11eb-8b43-07a46832f332.png)

**Comment by vauvenal5** [comment]
What do you mean by you do not have SSL? Ary you accessing your Nextcloud via http or https?

**Comment by realquink** [comment]
Accessing it locally via http.  So like:  http://192.168.1.x

**Comment by vauvenal5** [comment]
I see. That is not supported by Nextcloud Yaga. You have to have at least a self-signed certificate.

**Comment by realquink** [comment]
Ok thanks

**Comment by realquink** [comment]
Ok thanks. If its an easy change, would love if it could be updated to work like Nextcloud Talk, Notes, etc that allow you to do it via http without a cert.

**Comment by vauvenal5** [comment]
I am not a big fan of this. So I will probably not support this. See the thing is per default Android requires you to use https connections to backend services. If you want access to http you have specifically to mark this in the app manifest. Which is of course possible, however, it opens a set of vulnerabilities for less experienced users.

I recommend setting up your instance with a self-signed cert. In the official Nextcloud Docker examples there is even an example with a Docker container prepared for generating certs.

**Comment by vauvenal5** [comment]
Feel free to reopen this if you feel further discussion is necessary.
