### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by flexibeast** [vauvenal5/yaga#96]
Using Motorola moto e5 (Android 8.0.0).

After adding the URL of my server, `my.server.tld:port/nextcloud/`, where `port` is a non-well-known port (i.e. > 1024), the "Sign in..." screen in presented without content. Eventually it simply times out.

i am able to successfully log in to the server via a browser on the phone, as well as via the 'Nextcloud Dev' app.

**Comment by vauvenal5** [comment]
Have you tried the `Open in Browser` workflow from Yaga?
Edit: Which Yaga version are you using?

**Comment by flexibeast** [comment]
i hadn't tried that - yes, using the "Open in Browser", i'm able to log in successfully. Nothing at all is displayed in the "Home View", though "Browse View" seems to work fine.

Sorry, i should have mentioned i'm using v0.22.3.

**Comment by vauvenal5** [comment]
For the `Home View` you have to go into settings and set the folder that you want to be displayed by default. See also https://vauvenal5.github.io/yaga-docs/quickstart/#set-home-view-path

**Comment by vauvenal5** [comment]
Are you working with a self-signed cert or do you have a properly signed certificate?

**Comment by flexibeast** [comment]
i'm using a self-signed cert. i run my server via a consumer 'net connection, with my ISP blocking ports 80 and 443 by default; and i've found trying to use Let's Encrypt in this context to be more trouble than it's worth. 

There's no 'Path' setting visible:

![Screenshot_20210313-232535](https://user-images.githubusercontent.com/190652/111029955-c4923400-8453-11eb-8640-54323c37c871.png)

**Comment by vauvenal5** [comment]
Sorry I did not describe it clearly enough. You have to go to the view local settings. You will find them in the menu when clicking on the three dots, top right corner.

Regarding self-signed cert: That is fine, however, you will have to always login with the browser flow since the other flow over the build in view does not support self-signed certs. I probably should improve the usability on this one.

Regarding Lets Encrypt. They now also support a DNS based flow where your setup does not have to expose any ports. Just a heads up.

**Comment by vauvenal5** [comment]
Tracking usability issue here: #100

**Comment by flexibeast** [comment]
> You have to go to the view local settings. You will find them in the menu when clicking on the three dots, top right corner.

Ah! Great, thanks for your help. :-)

> however, you will have to always login with the browser flow since the other flow over the build in view does not support self-signed certs. 

Fair enough, no worries.

> Regarding Lets Encrypt. They now also support a DNS based flow where your setup does not have to expose any ports.

Yes, i seem to recall looking into that, but that it required write access to the relevant DNS record? i use a Dynamic DNS provider, which doesn't provide such access.
