### ISSUE TITLE
[FR] Add second confirmation after clicking "Delete remotely"

### ISSUE THREAD

**Issue by stavros-k** [vauvenal5/yaga#99]
I'd like to see some extra "stopping" point before you delete remotely something. Either a check box in the current dialog, or another pop up after clicking delete remotely. Preferably the next popup wont have the delete button on the same spot!

This is not a priority FR anyway. As you can always restore the files from the Trash on nextcloud web.

**Comment by vauvenal5** [comment]
The Nextcloud Files app has also only one dialog. I do not think that I will add a 2nd one as long as the main Nextcloud app is fine with one.

Anyway why do you thing a 2nd dialog is necessary?

**Comment by stavros-k** [comment]
> The Nextcloud Files app has also only one dialog. I do not think that I will add a 2nd one as long as the main Nextcloud app is fine with one.

I haven't try to delete something on the app , haven't noticed until you mentioned it. 

> Anyway why do you thing a 2nd dialog is necessary?

Piece of mind mostly, I have deleted manythings in my life because i did it too fast and misclicked or tapped :D
But i believe it's nice to have a confirmation for more "permanent actions"

**Comment by vauvenal5** [comment]
My suggestion at this point is as follows: I will close the issue for the time being. If enough people actually request a 2nd dialog I will reconsider this.

**Comment by stavros-k** [comment]
Sure, no problem!
